import { AuditAction } from "../enum/audit-action.enum";

/**
 * Domain table: audit_logs
 * Pure representation (no TypeORM dependency) of the audit table.
 * Mirrors 1:1 the structure created in infra/database/migrations/1710000000000-CreateAuditLogs.ts
 * and mapped in infra/database/entities/audit-log.entity.ts
 */
export class AuditLog {
  constructor(
    /** PK uuid generated by gen_random_uuid() */
    public id: string,
    /** Name of the audited entity, e.g. 'collect' */
    public entityName: string,
    /** Logical FK to the entity, e.g. collect.id */
    public entityId: string | null,
    /** Audited action */
    public action: AuditAction,
    /** Snapshot before the operation (null on CREATE) */
    public oldData: Record<string, unknown> | null,
    /** Snapshot after the operation (null on DELETE) */
    public newData: Record<string, unknown> | null,
    /** Creation timestamp */
    public createdAt: Date,
  ) {}
}
